

package ai_pro;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Vish Version
 */
public class Main extends javax.swing.JFrame {

    public Main() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_easy = new javax.swing.JLabel();
        jLabel_medium = new javax.swing.JLabel();
        jLabel_hard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".Dot Game....");
        setResizable(false);

        jLabel_easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai_pro/lev1.gif"))); // NOI18N
        jLabel_easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_easyMouseClicked(evt);
            }
        });

        jLabel_medium.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel_medium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai_pro/lev2.gif"))); // NOI18N
        jLabel_medium.setText("Easy");
        jLabel_medium.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel_medium.setOpaque(true);
        jLabel_medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_mediumMouseClicked(evt);
            }
        });

        jLabel_hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai_pro/lev3.gif"))); // NOI18N
        jLabel_hard.setText("Hard");
        jLabel_hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_hardMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48));
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".Dots Game...");
        jLabel4.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai_pro/settings.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_medium, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_easy, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_hard, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel_medium, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_easy, javax.swing.GroupLayout.PREFERRED_SIZE, 212, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_hard, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_mediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_mediumMouseClicked
       if(SettingsPage.music==1) new Sound().play("sounds/box.wav");
       fp.setVisible(false);
       LineClass.counter=0;
       BoxClass.counter=0;
       new GamePageEasy(SettingsPage.n,SettingsPage.m);
    }//GEN-LAST:event_jLabel_mediumMouseClicked

    private void jLabel_easyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_easyMouseClicked
        if(SettingsPage.music==1) new Sound().play("sounds/box.wav");
        fp.setVisible(false);
        LineClass.counter=0;
        BoxClass.counter=0;
        new GamePageMedium(SettingsPage.n,SettingsPage.m);
    }//GEN-LAST:event_jLabel_easyMouseClicked

    private void jLabel_hardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hardMouseClicked
        if(SettingsPage.music==1) new Sound().play("sounds/box.wav");
        fp.setVisible(false);
        LineClass.counter=0;
        BoxClass.counter=0;
        new GamePageHard(SettingsPage.n,SettingsPage.m);
    }//GEN-LAST:event_jLabel_hardMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(SettingsPage.music==1) new Sound().play("sounds/box.wav");
        fp.setVisible(false);
        LineClass.counter=0;
        BoxClass.counter=0;
        sp.setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static Main fp;
    public static SettingsPage sp;

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fp=new Main();
                sp=new SettingsPage();
                fp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_easy;
    private javax.swing.JLabel jLabel_hard;
    private javax.swing.JLabel jLabel_medium;
    // End of variables declaration//GEN-END:variables

}
