

package ai_pro;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;

/**
 *
 * @author Vish Version
 */
public class SettingsPage extends javax.swing.JFrame {

    public static int m=10,n=8,music=1,player=1;
    public static String userName="User Name";
    public static Color col_button=Color.white,col_user=Color.gray,col_com=Color.darkGray,col_dot=Color.lightGray;
    public static Color col_lab_com=new Color(82,127,186),col_lab_user=new Color(130,185,191);

    public SettingsPage() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider_m = new javax.swing.JSlider();
        jSlider_n = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxColor_button = new javax.swing.JButton();
        name_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        soundON_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        soundOFF_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lineColor_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        button_player2 = new javax.swing.JButton();
        button_player1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".Dot Game.....Settings");
        setBackground(new java.awt.Color(153, 204, 255));
        setResizable(false);

        jSlider_m.setForeground(new java.awt.Color(153, 153, 153));
        jSlider_m.setMajorTickSpacing(4);
        jSlider_m.setMaximum(26);
        jSlider_m.setMinimum(2);
        jSlider_m.setMinorTickSpacing(1);
        jSlider_m.setPaintLabels(true);
        jSlider_m.setPaintTicks(true);
        jSlider_m.setSnapToTicks(true);
        jSlider_m.setValue(10);

        jSlider_n.setForeground(new java.awt.Color(153, 153, 153));
        jSlider_n.setMajorTickSpacing(4);
        jSlider_n.setMaximum(26);
        jSlider_n.setMinimum(2);
        jSlider_n.setMinorTickSpacing(1);
        jSlider_n.setPaintLabels(true);
        jSlider_n.setPaintTicks(true);
        jSlider_n.setValue(10);

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48));
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".Dots Game...");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Row(M):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Col(N):");

        boxColor_button.setBackground(new java.awt.Color(153, 204, 255));
        boxColor_button.setFont(new java.awt.Font("Tahoma", 1, 18));
        boxColor_button.setForeground(new java.awt.Color(0, 102, 153));
        boxColor_button.setText("Box Color");
        boxColor_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxColor_buttonMouseClicked(evt);
            }
        });
        boxColor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxColor_buttonActionPerformed(evt);
            }
        });

        name_field.setFont(new java.awt.Font("Tahoma", 0, 24));
        name_field.setForeground(new java.awt.Color(102, 102, 102));
        name_field.setText("Write Your Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Color : ");

        soundON_button.setBackground(new java.awt.Color(0, 51, 51));
        soundON_button.setFont(new java.awt.Font("Times New Roman", 1, 18));
        soundON_button.setForeground(new java.awt.Color(255, 255, 255));
        soundON_button.setText("Turn ON");
        soundON_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundON_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel6.setText("or");

        soundOFF_button.setBackground(new java.awt.Color(153, 0, 51));
        soundOFF_button.setFont(new java.awt.Font("Times New Roman", 1, 18));
        soundOFF_button.setForeground(new java.awt.Color(255, 255, 255));
        soundOFF_button.setText("Turn OFF");
        soundOFF_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOFF_buttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sound :");

        lineColor_button.setBackground(new java.awt.Color(153, 204, 255));
        lineColor_button.setFont(new java.awt.Font("Tahoma", 1, 18));
        lineColor_button.setForeground(new java.awt.Color(0, 102, 153));
        lineColor_button.setText("Line Color");
        lineColor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineColor_buttonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai_pro/done.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Player :");

        button_player2.setBackground(new java.awt.Color(153, 204, 255));
        button_player2.setFont(new java.awt.Font("Tahoma", 1, 18));
        button_player2.setForeground(new java.awt.Color(0, 102, 153));
        button_player2.setText("2nd Player");
        button_player2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_player2MouseClicked(evt);
            }
        });
        button_player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_player2ActionPerformed(evt);
            }
        });

        button_player1.setBackground(new java.awt.Color(153, 204, 255));
        button_player1.setFont(new java.awt.Font("Tahoma", 1, 18));
        button_player1.setForeground(new java.awt.Color(0, 102, 153));
        button_player1.setText("1st Player");
        button_player1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_player1MouseClicked(evt);
            }
        });
        button_player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_player1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_n, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(jSlider_m, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(button_player1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boxColor_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(soundON_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soundOFF_button, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(lineColor_button, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(button_player2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(boxColor_button)
                            .addComponent(lineColor_button))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(soundON_button)
                            .addComponent(soundOFF_button)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(button_player2)
                            .addComponent(button_player1)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSlider_n, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        LineClass.counter=0;
        BoxClass.counter=0;
        m=jSlider_m.getValue()-1;
        n=jSlider_n.getValue()-1;
        userName=name_field.getText();
        System.out.println(userName);
        Main.fp.setVisible(true);
        Main.sp.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void boxColor_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxColor_buttonMouseClicked

    }//GEN-LAST:event_boxColor_buttonMouseClicked

    private void lineColor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineColor_buttonActionPerformed

        Color newColor = JColorChooser.showDialog(this, "Select Drawing Color", col_user);

        if (newColor != null) {
            col_user = newColor;
        }
    }//GEN-LAST:event_lineColor_buttonActionPerformed

    private void boxColor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxColor_buttonActionPerformed
        
        Color newColor = JColorChooser.showDialog(this, "Select Drawing Color", col_lab_user);

        if (newColor != null) {
            col_lab_user= newColor;
        }
    }//GEN-LAST:event_boxColor_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LineClass.counter=0;
        BoxClass.counter=0;
        m=jSlider_m.getValue()-1;
        n=jSlider_n.getValue()-1;
        userName=name_field.getText();
        System.out.println(userName);
        Main.fp.setVisible(true);
        Main.sp.setVisible(false);
        System.out.println(" n  "+ SettingsPage.n);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void soundON_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundON_buttonActionPerformed
        music=1;
    }//GEN-LAST:event_soundON_buttonActionPerformed

    private void soundOFF_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOFF_buttonActionPerformed
        music=0;
    }//GEN-LAST:event_soundOFF_buttonActionPerformed

    private void button_player2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_player2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_player2MouseClicked

    private void button_player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_player2ActionPerformed
        player=2;
    }//GEN-LAST:event_button_player2ActionPerformed

    private void button_player1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_player1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_player1MouseClicked

    private void button_player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_player1ActionPerformed
        player=1;
    }//GEN-LAST:event_button_player1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        LineClass.counter=0;
        BoxClass.counter=0;
        m=jSlider_m.getValue()-1;
        n=jSlider_n.getValue()-1;
        userName=name_field.getText();
        System.out.println(userName);
        Main.fp.setVisible(true);
        Main.sp.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SettingsPage().setVisible(true);
//            }
//        });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boxColor_button;
    private javax.swing.JButton button_player1;
    private javax.swing.JButton button_player2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider_m;
    private javax.swing.JSlider jSlider_n;
    private javax.swing.JButton lineColor_button;
    private javax.swing.JTextField name_field;
    private javax.swing.JButton soundOFF_button;
    private javax.swing.JButton soundON_button;
    // End of variables declaration//GEN-END:variables

}
